// Udyam Saarthi — Tier-0 RAG: stream a citation-grounded answer over all 225 MSME profiles.
// Corpus (~45K tokens, grows with enrichments) rides in a prompt-cached prefix; no retrieval needed.
// Regenerate corpus-latest.json with: npm run rag:build
import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic(); // ANTHROPIC_API_KEY from env

const SYSTEM =
  "You are Udyam Saarthi — an AI guide for India's aspiring entrepreneurs. " +
  "Answer questions ONLY using the provided PMRY/DCMSME government business model profiles. " +
  "Rules: " +
  "1. Never invent or estimate figures not in the profiles. " +
  "2. Always cite: the profile title (e.g. 'Vol I ch15 — Hair Brushes'). " +
  "3. Show both 2003 original AND 2026-adjusted (×4 CPI) figures when quoting capital or profit. " +
  "4. For 'best/top/cheapest' queries: show a ranked comparison table with at most 5 rows. " +
  "5. For capital filter queries: include all profiles within ±20% of the stated budget. " +
  "6. End every answer with: Source: Government of India, DC(MSME) PMRY Project Profiles. " +
  "7. If the question is outside scope (not about MSME business models): say so clearly and suggest a rephrasing.";

// Process-scoped corpus cache — loaded once per serverless container, not per request
let DOCS: ReturnType<typeof loadDocs> | null = null;

type DocBlock = {
  type: "document";
  source: { type: "text"; media_type: "text/plain"; data: string };
  title: string;
  citations: { enabled: boolean };
  cache_control?: { type: "ephemeral" };
};

function loadDocs(): DocBlock[] {
  // corpus-latest.json is generated by npm run rag:build and gitignored
  // In Vercel it's built during the build step via rag:build in the build command
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const corpus = require("./corpus-latest.json") as {
    documents: DocBlock[];
  };
  return corpus.documents as DocBlock[];
}

export function getDocBlocks(): DocBlock[] {
  if (!DOCS) DOCS = loadDocs();
  return DOCS;
}

export type Cite = { profile?: string; quote?: string };
export type AnswerChunk = { text?: string; citation?: Cite };

/** Yields text deltas and citations as they stream. */
export async function* answer(question: string): AsyncGenerator<AnswerChunk> {
  const docs = getDocBlocks();

  const stream = client.messages.stream({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 2048,
    system: [{ type: "text", text: SYSTEM, cache_control: { type: "ephemeral" } }],
    // citations are incompatible with JSON mode — do not add output_config here
    messages: [{ role: "user", content: [...docs, { type: "text", text: question }] }],
  });

  for await (const ev of stream) {
    if (ev.type === "content_block_delta") {
      if (ev.delta.type === "text_delta") yield { text: ev.delta.text };
      else if (ev.delta.type === "citations_delta") {
        const c = (ev.delta as unknown as { citation: { document_title?: string; cited_text?: string } }).citation;
        yield { citation: { profile: c?.document_title, quote: c?.cited_text } };
      }
    }
  }

  const final = await stream.finalMessage();
  if (final.stop_reason === "refusal") {
    yield { text: "\n[Udyam Saarthi could not answer this request. Please rephrase your question.]" };
  }
}
